<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Chat extends Model
{
    /**
     * Stop primary key being cast as an integer
     *
     * @var bool
     */
    public $incrementing = false;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'id', 'first_name', 'last_name',
    ];

    /**
     * Specify the name of the table.
     *
     * @var string
     */
    public $table = 'chat';

    /**
     * Get current users command status
     * @return \Illuminate\Database\Eloquent\Relations\HasOne
     */
    public function commandStatus()
    {
        return $this->hasOne(CommandStatus::class);
    }

    public function aliases()
    {
        return $this->hasMany(Alias::class);
    }

    public function __call($method, $parameters)
    {
        return parent::__call($method, $parameters); // TODO: Change the autogenerated stub
    }
}
